### ISSUE TITLE
Yocto/Bitbake build fails since 1.5.6

### ISSUE THREAD

**Issue by gravufo** [fluent/fluent-bit#4204]
## Bug Report

**Describe the bug**
Trying to build the latest version of fluent-bit using the provided yocto recipe and it fails. I can only manage to compile v1.5.6. Anything above that fails.

**To Reproduce**
- Steps to reproduce the problem:
Take the latest .bb recipe from the repo and try to compile it in a yocto project.

**Expected behavior**
Should compile as-is.

**Comment by gravufo** [comment]
The error seems to be:
```
| configure: error: in `/home/dev/repo/targets/hyperv/tmp/work/core2-64-poky-linux/fluent-bit/1.8.8-r0/git/lib/onigmo':
| configure: error: cannot run C compiled programs.
| If you meant to cross compile, use `--host'.
| See `config.log' for more details
| make[2]: *** [CMakeFiles/onigmo.dir/build.make:107: onigmo-prefix/src/onigmo-stamp/onigmo-configure] Error 1
| make[2]: Leaving directory '/home/dev/repo/targets/hyperv/tmp/work/core2-64-poky-linux/fluent-bit/1.8.8-r0/build'
| make[1]: *** [CMakeFiles/Makefile2:2956: CMakeFiles/onigmo.dir/all] Error 2
```

**Comment by gravufo** [comment]
Kind of sad, this bug has been reported in the past  (#3133) and no one seems to care.

**Comment by siqjonathan** [comment]
v1.6.9 is the last I can build under Yocto. Unfortunately in v1.6.9 the included library mbedtls 2.24.0 has compilation errors with the toolchain in newer versions of Yocto so I'm trying to find a solution to this problem. v1.8.0 moved to 2.26.0 and v1.8.4 to 2.27.0. 2.27.0 compiles with newer toolchain (gcc 11.2) but onigmo and backtrace give above error seeming to indicate they didn't get the message it's a cross-compilation. I get the same problem with backtrace and onigmo building using older compiler (gcc 9.2).

**Comment by siqjonathan** [comment]
This problem was introduced in v1.8.0 with this commit: bfce2316d93a3ead43965d5034676200269f93c0

**Comment by gravufo** [comment]
@edsiper are there any plans on fixing this?

**Comment by cveilleux** [comment]
I tried all releases. Tried enabling/disabling a bunch of input/output plugins. In the end @gravufo's comment is still valid, the latest version I've been able to build on yocto is v1.5.6. I am using dunfell.

**Comment by victordiezvera** [comment]
I've the same problem. Seems that host property is duplicated. Changing cmakes to use the correct host in configure(with the property ${AUTOCONF_HOST_OPT} is enough as in 1.5.6, so removing   -host="${host}" from onigmo.cmake and main CMakeList), seems that this configure is perform correctly, but then, the compilation fails due to missing libraries as stdlib.h in onigmo and math.h on jemalloc. Any idea if this problem is going to be solved? also last version working for mi is 1.5.6.

**Comment by patrick-stephens** [comment]
I'm afraid I'm not a Yocto expert but I would say if you have a PR to submit that would really help to get it into a release. If you submit them and ping me I can try to push them through.

**Comment by ptsneves** [comment]
Hello
I was successful in building 1.8.9 with some adaptations:
1. build: support native cross-compilation for ARM64](https://github.com/fluent/fluent-bit/commit/bfce2316d93a3ead43965d5034676200269f93c0) should be reverted.
2. FORTIFY_SOURCE  should be disabled as this will conflict with the lack of -O level in libbacktrace. 
3. cmake/linux-arm64.cmake hardcodes host paths which are distribution dependent in CMAKE_FIND_ROOT_PATH

The diagnostic of @victordiezvera  was almost spot on. The commit should be reverted because it is wrong to add extra flags that should be part of the AUTOCONF_HOST_OPT. Reverting the change will allow for most of the issues to go away
The stdlib errors were misleading and due to the fact that yocto set FORTIFY_SOURCE=2 by default but that also requires -O settings, which for reasons I did not examine, is not passed. The error is something like:
```
 error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
```

The following recipe worked for me. If anybody has issues making it or with building fluent-bit through yocto I am available to help out. I will also try to get a PR, although I am not sure how it is possible for the recipe to point to a release that does not exist, like we currently have in master PV=1.9.0

```
# Fluent Bit - Yocto / Bitbake
# ============================
# The following Bitbake package the latest Fluent Bit stable release.

SUMMARY = "Fast Log processor and Forwarder"
DESCRIPTION = "Fluent Bit is a data collector, processor and  \
forwarder for Linux. It supports several input sources and \
backends (destinations) for your data. \
"

HOMEPAGE = "http://fluentbit.io"
BUGTRACKER = "https://github.com/fluent/fluent-bit/issues"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2ee41112a44fe7014dce33e26468ba93"
SECTION = "net"

PR = "r0"
PV = "1.8.9"

SRCREV = "v${PV}"
SRC_URI = "git://github.com/fluent/fluent-bit.git;nobranch=1 \
    "

S = "${WORKDIR}/git"
DEPENDS = "zlib bison-native flex-native openssl"
DEPENDS_append_libc-musl = " fts "

INSANE_SKIP_${PN}-dev += "dev-elf"

# Use CMake 'Unix Makefiles' generator
OECMAKE_GENERATOR ?= "Unix Makefiles"

# Fluent Bit build options
# ========================

# Host related setup
EXTRA_OECMAKE += "-DGNU_HOST=${HOST_SYS} -DFLB_ALL=ON -DFLB_TD="

# Disable LuaJIT and filter_lua support
EXTRA_OECMAKE += "-DFLB_LUAJIT=Off -DFLB_FILTER_LUA=Off "

# Disable Library and examples
EXTRA_OECMAKE += "-DFLB_SHARED_LIB=Off -DFLB_EXAMPLES=Off "

# Systemd support (optional)
EXTRA_OECMAKE += "${@bb.utils.contains('DISTRO_FEATURES','systemd','-DFLB_SYSTEMD=On','',d)}"

# Kafka Output plugin (disabled by default): note that when
# enabling Kafka output plugin, the backend library librdkafka
# requires 'openssl' as a dependency.
#
# DEPENDS += "openssl "
# EXTRA_OECMAKE += "-DFLB_OUT_KAFKA=On "

inherit cmake systemd features_check

SYSTEMD_SERVICE_${PN} = "td-agent-bit.service"
TARGET_CC_ARCH_append = " ${SELECTED_OPTIMIZATION}"
TARGET_CC_ARCH_remove = "-D_FORTIFY_SOURCE=2"

```

**Comment by ptsneves** [comment]
Hello
I was successful in building 1.8.9 with some adaptations:

    build: support native cross-compilation for ARM64](bfce231) should be reverted.
    FORTIFY_SOURCE should be disabled as this will conflict with the lack of -O level in libbacktrace.
    cmake/linux-arm64.cmake hardcodes host paths which are distribution dependent in CMAKE_FIND_ROOT_PATH

The diagnostic of @victordiezvera was almost spot on. The commit should be reverted because it is wrong to add extra flags that should be part of the AUTOCONF_HOST_OPT. Reverting the change will allow for most of the issues to go away
The stdlib errors were misleading and due to the fact that yocto set FORTIFY_SOURCE=2 by default but that also requires -O settings, which for reasons I did not examine, is not passed. The error is something like:

 error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

If anybody has issues making the recipe or with building fluent-bit through yocto I am available to help out.

EDIT: I am not able to contribute the recipe itself due to legal constraints but I can guide whoever picks up on the hints I left.

**Comment by siqjonathan** [comment]
See my note above. Doing this should remove the FORTIFY_SOURCE error, which is due to default of debug settings which turns of -O. So we want release target which has -O.

EXTRA_OECMAKE += "-DFLB_DEBUG=Off "
EXTRA_OECMAKE += "-DFLB_RELEASE=On "

**Comment by cveilleux** [comment]
Here is a working v1.8.9 recipe and required patch to revert bfce231.

https://gist.github.com/cveilleux/b1f19cf8580cb805f7c49a0556130a82

Tested under dunfell.

@siqjonathan I have enabled FLB_RELEASE and disabled FLB_DEBUG as per your suggestion, but it is not enough to get all bundled libs to compile. The following did the trick:

```
TARGET_CC_ARCH_append = " ${SELECTED_OPTIMIZATION}"
TARGET_CC_ARCH_remove = "-D_FORTIFY_SOURCE=2"
```

Many thanks to @ptsneves

**Comment by patrick-stephens** [comment]
Nice, sounds like you've got something going @cveilleux
Are you able to submit a PR for it? We cannot just copy in your gist to the OSS project as it may impact copyright or licensing concerns so we just need to ensure it goes through the PR process.

**Comment by cveilleux** [comment]
The main blocker is that bfce231 needs to be reverted.

I will submit a PR for that first. This will avoid providing a recipe that requires a patch.

**Comment by siqjonathan** [comment]
My recipe currently looks like this:

```
# Fluent Bit - Yocto / Bitbake
# ============================
# The following Bitbake package the latest Fluent Bit stable release.

SUMMARY = "Fast Log processor and Forwarder"
DESCRIPTION = "Fluent Bit is a data collector, processor and  \
forwarder for Linux. It supports several input sources and \
backends (destinations) for your data. \
"

HOMEPAGE = "http://fluentbit.io"
BUGTRACKER = "https://github.com/fluent/fluent-bit/issues"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2ee41112a44fe7014dce33e26468ba93"
SECTION = "net"

PR = "r0"

SRCREV = "v${PV}"
SRC_URI = "git://github.com/fluent/fluent-bit.git;nobranch=1"
SRC_URI += "file://0001-Revert-build-onigmo-macos-Specify-isysroot-on-CC-to-.patch"
SRC_URI += "file://0002-Revert-build-support-native-cross-compilation-for-AR.patch"

S = "${WORKDIR}/git"
DEPENDS = "zlib bison-native flex-native openssl"
INSANE_SKIP:${PN}-dev += "dev-elf"

# Use CMake 'Unix Makefiles' generator
OECMAKE_GENERATOR ?= "Unix Makefiles"

# Fluent Bit build options
# ========================

# Host related setup
EXTRA_OECMAKE += "-DGNU_HOST=${HOST_SYS} "

# Disable LuaJIT and filter_lua support
EXTRA_OECMAKE += "-DFLB_LUAJIT=Off -DFLB_FILTER_LUA=Off "

# Disable Library and examples
EXTRA_OECMAKE += "-DFLB_SHARED_LIB=Off -DFLB_EXAMPLES=Off "

# disable systemd
EXTRA_OECMAKE += "-DFLB_IN_SYSTEMD=${@bb.utils.contains('DISTRO_FEATURES', 'systemd', 'On', 'Off', d)} "

# use correct compilation flags
EXTRA_OECMAKE += "-DFLB_DEBUG=Off "
EXTRA_OECMAKE += "-DFLB_RELEASE=On "

# Systemd support (optional)
DEPENDS += "${@bb.utils.contains('DISTRO_FEATURES', 'systemd', 'systemd', '', d)}"
EXTRA_OECMAKE += "${@bb.utils.contains('DISTRO_FEATURES', 'systemd', ' -DFLB_IN_SYSTEMD=On ', '', d)}"

# Kafka Output plugin (disabled by default): note that when
# enabling Kafka output plugin, the backend library librdkafka
# requires 'openssl' as a dependency.
#
# DEPENDS += "openssl "
# EXTRA_OECMAKE += "-DFLB_OUT_KAFKA=On "

inherit cmake ${@bb.utils.contains('DISTRO_FEATURES', 'systemd', 'systemd', '', d)}

SYSTEMD_SERVICE:${PN} = "fluent-bit.service"
TARGET_CC_ARCH:append = " ${SELECTED_OPTIMIZATION}"

FILES:${PN} += "/lib/systemd/system"
```

**Comment by patrick-stephens** [comment]
It would also be great to get some of the useful info here into the docs to support others: https://docs.fluentbit.io/manual/installation/yocto-embedded-linux

@cveilleux or anyone, would you be ok to do a PR for https://github.com/fluent/fluent-bit-docs/blob/master/installation/yocto-embedded-linux.md? I could but I'm no expert and you all know the specifics.

**Comment by gravufo** [comment]
Not stale.

**Comment by patrick-stephens** [comment]
What still needs doing here? Apologies but I have no way to test it so need some guidance. 
Looks like we have merged a few related PRs, is there more @gravufo or @cveilleux . Please can you add the details.

**Comment by gravufo** [comment]
> What still needs doing here? Apologies but I have no way to test it so need some guidance. Looks like we have merged a few related PRs, is there more @gravufo or @cveilleux . Please can you add the details.

My apologies, I hadn't noticed there was a PR merged linked to this issue (I checked too fast on mobile). I haven't tested it, but from a quick glance at the changes, it should do the job.

I'll let someone else close this issue, since I won't be able to test it in the next few days :(

Thanks!

**Comment by ptsneves** [comment]
I will try to sync the recipe with meta-oe

**Comment by patrick-stephens** [comment]
Let me know if you need anything @ptsneves although I don't have any way to test it but if you need me to poke CI let me know!

**Comment by ptsneves** [comment]
Hey @patrick-stephens, i see the current bitbake recipe is for 2.0.0 but this is not released yet as far as i see. Can you confirm? In bitbake there is a preference for released tarballs like in http://fluentbit.io/releases/1.3/fluent-bit-${PV}.tar.gz

**Comment by patrick-stephens** [comment]
Yeah, as always the `master` branch is prepared for the next release rather than the current release.

**Comment by patrick-stephens** [comment]
Not sure what you're after for source but this is the latest discussion on what is produced: https://github.com/fluent/fluent-bit/issues/5328#issuecomment-1161508629

**Comment by ptsneves** [comment]
@patrick-stephens I now understand the current 2.0.0 version and am fine with it. I will just submit a pull request for it to use the tarball version. It does not matter it does not exist because the git reference v2.0.0 [mentioned in the recipe](https://github.com/fluent/fluent-bit/blob/c83050facc32f50cc0e0268d93a08eb6fefebb3d/fluent-bit_2.0.0.bb#L21) also does not exist yet. I assume it will exist once there is a 2.0.0 release.

I also see that https://github.com/fluent/fluent-bit/blob/master/fluent-bit_git.bb#L21 is out of date and I will try to update it. Thanks for your fast feedback.
