### ISSUE TITLE
GCC 10: unable to compile 1.4.5 on Archlinux

### ISSUE THREAD

**Issue by bastelfreak** [fluent/fluent-bit#2223]
## Bug Report

**Describe the bug**

I'm unable to compile fluent-bit 1.4.5 on Archlinux

**To Reproduce**

* Start Arch in Docker/their official virtualbox image / install it on bare metal
* Install dependencies:

```sh
pacman -Syu cmake postgresql-libs postgresql python valgrind gtest doxygen graphviz
```

* download 1.4.5 tarball

```sh
mkdir build
cd build
cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DFLB_TESTS_INTERNAL=Yes \
        -DFLB_TESTS_RUNTIME=Yes \
        -DFLB_IN_MQTT=Yes \
        -DFLB_TLS=Yes \
        -DFLB_ALL=Yes \
        -DFLB_OUT_NATS=Yes \
        ..
make
```

**Expected behavior**

I expect it to compile

cmake output:

```
- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Found Journald: /usr/lib/libsystemd.so  
-- Found Monkey: /build/fluent-bit/src/fluent-bit-1.4.5/lib/monkey/include  
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/bin/bison (found version "3.6.2") 
-- Enabling FLB_REGEX since FLB_PARSER requires
-- Found GTest: /usr/lib/libgtest.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found Threads: TRUE  
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.18") found components: doxygen dot 
-- Performing Test CIO_HAVE_FALLOCATE
-- Performing Test CIO_HAVE_FALLOCATE - Success
-- Performing Test HAVE_STAT_H
-- Performing Test HAVE_STAT_H - Success
-- Performing Test HAVE_SYS_UIO_H
-- Performing Test HAVE_SYS_UIO_H - Success
-- Performing Test HAVE_UNISTD_H
-- Performing Test HAVE_UNISTD_H - Success
-- Performing Test HAVE_EPOLL
-- Performing Test HAVE_EPOLL - Success
-- Performing Test HAVE_KQUEUE
-- Performing Test HAVE_KQUEUE - Failed
-- Performing Test HAVE_TIMERFD_CREATE
-- Performing Test HAVE_TIMERFD_CREATE - Success
-- Performing Test HAVE_EVENTFD
-- Performing Test HAVE_EVENTFD - Success
-- Performing Test MK_HAVE_MEMRCHR
-- Performing Test MK_HAVE_MEMRCHR - Success
-- Found PythonInterp: /usr/bin/python (found version "3.8.3") 
-- Performing Test FLB_HAVE_VALGRIND
-- Performing Test FLB_HAVE_VALGRIND - Success
-- Performing Test FLB_HAVE_FORK
-- Performing Test FLB_HAVE_FORK - Success
-- Performing Test FLB_HAVE_TIMESPEC_GET
-- Performing Test FLB_HAVE_TIMESPEC_GET - Success
-- Performing Test FLB_HAVE_GMTOFF
-- Performing Test FLB_HAVE_GMTOFF - Success
-- Performing Test FLB_HAVE_CLOCK_GET_TIME
-- Performing Test FLB_HAVE_CLOCK_GET_TIME - Failed
-- Performing Test FLB_HAVE_UNIX_SOCKET
-- Performing Test FLB_HAVE_UNIX_SOCKET - Success
-- Found PostgreSQL: /usr/lib/libpq.so (found version "12.3") 
-- Performing Test FLB_HAVE_C_TLS
-- Performing Test FLB_HAVE_C_TLS - Success
-- Performing Test FLB_HAVE_ACCEPT4
-- Performing Test FLB_HAVE_ACCEPT4 - Success
-- Performing Test FLB_HAVE_INOTIFY
-- Performing Test FLB_HAVE_INOTIFY - Success
-- Looking for accept4
-- Looking for accept4 - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /build/fluent-bit/src/fluent-bit-1.4.5/build
```

The make output is too long for github, you can see the full output here: https://gist.github.com/bastelfreak/6f48e9a6bc975051a09fb41170232d8a

There are basically a few hundred lines from ld:

```
/usr/bin/ld: ../../library/libflb-plugin-out_es.a(es.c.o):/build/fluent-bit/src/fluent-bit-1.4.5/include/fluent-bit/flb_thread_libco.h:66: multiple definition of `flb_thread_key'; CMakeFiles/flb-it-stream_processor.dir/stream_processor.c.o:/build/fluent-bit/src/fluent-bit-1.4.5/include/fluent-bit/flb_thread_libco.h:66: first defined here
```

**Comment by thkukuk** [comment]
In short: fluent-bit does not compile with gcc 10. On no distribution, not only not on Archlinux.

**Comment by bastelfreak** [comment]
Hi,
I was able to compile it with gcc 8.4. Do you know if there are any plans for gcc 10 support?

**Comment by edsiper** [comment]
I am checking where is the problem, likely related on how we link the stuff.

**Comment by edsiper** [comment]
related to this:

https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by edsiper** [comment]
I have done the required changes to fix the original problem (wrong declaration of global vars). Now it should be ok, GIT master builds with GCC 10 and the next v1.4.6 release (few days) comes with the backported fixes too.
