### PR TITLE
out_opentelemetry: make log records batch size to configurable

### LINKED ISSUE #6512: Fluent-Bit Crashes when using opentelemetry logs output (version 2.0.6)
## Bug Report

Fluent bit crashes when using the opentelemetry output plugin, but only with logs. If the dummy input is omitted, it will not crash

```
fluent-bit-fluent-bit-1     | Fluent Bit v2.0.6
fluent-bit-fluent-bit-1     | * Copyright (C) 2015-2022 The Fluent Bit Authors
fluent-bit-fluent-bit-1     | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit-fluent-bit-1     | * https://fluentbit.io
fluent-bit-fluent-bit-1     | 
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] Configuration:
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  flush time     | 1.000000 seconds
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  grace          | 5 seconds
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  daemon         | 0
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] ___________
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  inputs:
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]      node_exporter_metrics
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]      dummy
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] ___________
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  filters:
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] ___________
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  outputs:
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]      opentelemetry.0
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] ___________
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info]  collectors:
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [fluent bit] version=2.0.6, commit=211f841fe2, pid=1
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [storage] created root path /fluent-bit/run/buffer
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [storage] ver=1.3.0, type=memory+filesystem, sync=normal, checksum=off, max_chunks_up=128
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [storage] backlog input plugin: storage_backlog.2
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [cmetrics] version=0.5.7
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [ctraces ] version=0.2.5
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] initializing
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] storage_strategy='memory' (memory only)
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [node_exporter_metrics:node_exporter_metrics.0] created event channels: read=21 write=22
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] path.procfs = /proc
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] path.sysfs  = /sys
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:dummy:dummy.1] initializing
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:dummy:dummy.1] storage_strategy='memory' (memory only)
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [dummy:dummy.1] created event channels: read=23 write=24
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ warn] [input:dummy:dummy.1] data is incomplete. Use default string.
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:storage_backlog:storage_backlog.2] initializing
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:storage_backlog:storage_backlog.2] storage_strategy='memory' (memory only)
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [storage_backlog:storage_backlog.2] created event channels: read=25 write=26
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 95.4M
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [opentelemetry:opentelemetry.0] created event channels: read=27 write=28
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [router] match rule node_exporter_metrics.0:opentelemetry.0
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [router] match rule dummy.1:opentelemetry.0
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:58] [debug] [router] match rule storage_backlog.2:opentelemetry.0
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:59] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:59] [ info] [sp] stream processor started
fluent-bit-fluent-bit-1     | [2022/12/06 22:05:59] [debug] [input chunk] update output instances with new chunk size diff=26
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [task] created task=0x7fad3003e420 id=0 OK
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram0
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram1
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram2
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram3
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram4
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram5
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram6
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram7
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram8
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram9
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram10
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram11
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram12
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram13
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram14
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: ram15
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop0
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop1
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop2
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop3
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop4
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop5
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop6
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: loop7
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input:node_exporter_metrics:node_exporter_metrics.0] skip device: vda1
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input chunk] update output instances with new chunk size diff=48502
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [debug] [input chunk] update output instances with new chunk size diff=26
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [engine] caught signal (SIGSEGV)
fluent-bit-fluent-bit-1     | [2022/12/06 22:06:00] [engine] caught signal (SIGSEGV)
fluent-bit-fluent-bit-1     | #0  0x7fad3710c5bd      in  ???() at ???:0
fluent-bit-fluent-bit-1     | #1  0x7fad3710eed0      in  ???() at ???:0
fluent-bit-fluent-bit-1     | #2  0x561d83f05f7b      in  flb_calloc() at include/fluent-bit/flb_mem.h:88
fluent-bit-fluent-bit-1     | #3  0x561d83f0ab9e      in  flush_to_otel() at plugins/out_opentelemetry/opentelemetry.c:668
fluent-bit-fluent-bit-1     | #4  0x561d83f0aed9      in  process_logs() at plugins/out_opentelemetry/opentelemetry.c:762
fluent-bit-fluent-bit-1     | #5  0x561d83f0bb4c      in  cb_opentelemetry_flush() at plugins/out_opentelemetry/opentelemetry.c:992
fluent-bit-fluent-bit-1     | #6  0x561d83b2b4ca      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:524
fluent-bit-fluent-bit-1     | #7  0x561d84564b06      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
fluent-bit-fluent-bit-1     | #8  0xffffffffffffffff  in  ???() at ???:0
fluent-bit-fluent-bit-1 exited with code 139

```

## Steps to reproduce

run `docker-compose up` with the following files

docker-compose.yml
```yaml
version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit:2.0.6
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - opentelemetry

  opentelemetry:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1889:1888"   # pprof extension
      - "8893:8888"   # Prometheus metrics exposed by the collector
      - "8894:8889"   # Prometheus exporter metrics
      - "13134:13133" # health_check extension
      - "4322:4317"   # OTLP gRPC receiver
      - "4323:4318"   # OTLP http receiver
      - "55680:55679" # zpages extension
```

fluent-bit.conf
```
[SERVICE]
    Parsers_File    /fluent-bit/etc/parsers.conf
    HTTP_Server     On
    HTTP_Listen     0.0.0.0
    HTTP_Port       2020
    Health_Check    On
    storage.path    /fluent-bit/run/buffer
    storage.metrics on
    Log_Level       debug


[INPUT]
    Name                 node_exporter_metrics
    Tag                  node_metrics
    Scrape_interval      2


[INPUT]
    Name dummy
    Tag dummy.log
    Rate 1
    Dummy {"key": ["val1", 1, 2.3], "key2": "val2"}


[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 opentelemetry
    Port                 4318
    Metrics_uri          /v1/metrics
    Logs_uri             /v1/logs
    Traces_uri           /v1/traces
    Log_response_payload True
    Tls                  Off
    Tls.verify           Off

```

otel-collector-config.yaml
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        include_metadata: true

processors:
  batch:
  resource:
    attributes:
      - key: host.name
        value: "fluent bit"
        action: upsert

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  telemetry:
    logs:
      level: "debug"
      encoding: json
    metrics:
      level: detailed

  pipelines:
    metrics/multi:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging]
```

### PR DESCRIPTION
**Pull request by Syn3rman**
- Fix build warnings in the out_opentelemetry plugin
- Make batch size for configurable
- Reduce default value for batch size to 64 since it takes up a lot of memory 

Fixes #6512 & #6457 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change

```
[INPUT]
	Name dummy
	Tag dummy.log
	Rate 1
	Dummy {"key": ["val1", 1, 2.3, [4, 4.6, 2], {"mim": "mimvalue"}], "key2": "val2"}

[OUTPUT]
	name stdout
	match *

[OUTPUT]
	name opentelemetry
	match *
	host 0.0.0.0
	port 3434
	logs_uri /v1/logs
	metrics_uri /v1/metrics
	traces_uri /v1/traces
	batch_size 10
```

- [x] Debug log output from testing the change

```
root@171c1e35560a:/fluent-bit/build# ./bin/fluent-bit -c ../dev-files/confs/out_otel_logs.conf -v
Fluent Bit v2.0.7
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/12/15 07:55:26] [ info] Configuration:
[2022/12/15 07:55:26] [ info]  flush time     | 1.000000 seconds
[2022/12/15 07:55:26] [ info]  grace          | 5 seconds
[2022/12/15 07:55:26] [ info]  daemon         | 0
[2022/12/15 07:55:26] [ info] ___________
[2022/12/15 07:55:26] [ info]  inputs:
[2022/12/15 07:55:26] [ info]      dummy
[2022/12/15 07:55:26] [ info] ___________
[2022/12/15 07:55:26] [ info]  filters:
[2022/12/15 07:55:26] [ info] ___________
[2022/12/15 07:55:26] [ info]  outputs:
[2022/12/15 07:55:26] [ info]      stdout.0
[2022/12/15 07:55:26] [ info]      opentelemetry.1
[2022/12/15 07:55:26] [ info] ___________
[2022/12/15 07:55:26] [ info]  collectors:
[2022/12/15 07:55:26] [ info] [fluent bit] version=2.0.7, commit=91ebce5540, pid=13501
[2022/12/15 07:55:26] [debug] [engine] coroutine stack size: 196608 bytes (192.0K)
[2022/12/15 07:55:26] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/12/15 07:55:26] [ info] [cmetrics] version=0.5.7
[2022/12/15 07:55:26] [ info] [ctraces ] version=0.2.5
[2022/12/15 07:55:26] [ info] [input:dummy:dummy.0] initializing
[2022/12/15 07:55:26] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/12/15 07:55:26] [debug] [dummy:dummy.0] created event channels: read=21 write=22
[2022/12/15 07:55:26] [debug] [stdout:stdout.0] created event channels: read=23 write=24
[2022/12/15 07:55:26] [debug] [opentelemetry:opentelemetry.1] created event channels: read=30 write=31
[2022/12/15 07:55:26] [debug] [router] match rule dummy.0:stdout.0
[2022/12/15 07:55:26] [debug] [router] match rule dummy.0:opentelemetry.1
[2022/12/15 07:55:26] [ info] [output:stdout:stdout.0] worker #0 started
[2022/12/15 07:55:26] [ info] [sp] stream processor started
[2022/12/15 07:55:26] [debug] [input chunk] update output instances with new chunk size diff=68
[2022/12/15 07:55:27] [debug] [task] created task=0xffff94014e60 id=0 OK
[2022/12/15 07:55:27] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[0] dummy.log: [1671090926.974088388, {"key"=>["val1", 1, 2.300000, [4, 4.600000, 2], {"mim"=>"mimvalue"}], "key2"=>"val2"}]
[2022/12/15 07:55:27] [debug] [out flush] cb_destroy coro_id=0
[2022/12/15 07:55:27] [debug] [input chunk] update output instances with new chunk size diff=68
[2022/12/15 07:55:27] [debug] [http_client] not using http_proxy for header
[2022/12/15 07:55:27] [ info] [output:opentelemetry:opentelemetry.1] 0.0.0.0:3434, HTTP status=200


[2022/12/15 07:55:27] [debug] [out flush] cb_destroy coro_id=0
[2022/12/15 07:55:27] [debug] [task] destroy task=0xffff94014e60 (task_id=0)
^C[2022/12/15 07:55:28] [engine] caught signal (SIGINT)
[2022/12/15 07:55:28] [debug] [task] created task=0xffff94016390 id=0 OK
[2022/12/15 07:55:28] [debug] [output:stdout:stdout.0] task_id=0 assigned to thread #0
[2022/12/15 07:55:28] [ warn] [engine] service will shutdown in max 5 seconds
[2022/12/15 07:55:28] [ info] [input] pausing dummy.0
[0] dummy.log: [1671090927.968851930, {"key"=>["val1", 1, 2.300000, [4, 4.600000, 2], {"mim"=>"mimvalue"}], "key2"=>"val2"}]
[2022/12/15 07:55:28] [debug] [out flush] cb_destroy coro_id=1
[2022/12/15 07:55:28] [debug] [http_client] not using http_proxy for header
[2022/12/15 07:55:28] [ info] [output:opentelemetry:opentelemetry.1] 0.0.0.0:3434, HTTP status=200


[2022/12/15 07:55:28] [debug] [out flush] cb_destroy coro_id=1
[2022/12/15 07:55:28] [debug] [task] destroy task=0xffff94016390 (task_id=0)
[2022/12/15 07:55:28] [ info] [engine] service has stopped (0 pending tasks)
[2022/12/15 07:55:28] [ info] [input] pausing dummy.0
[2022/12/15 07:55:28] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/12/15 07:55:28] [ info] [output:stdout:stdout.0] thread worker #0 stopped
```

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

```
root@171c1e35560a:/fluent-bit/build# valgrind --leak-check=full ./bin/fluent-bit -c ../dev-files/confs/out_otel_logs.conf
==13495== Memcheck, a memory error detector
==13495== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13495== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==13495== Command: ./bin/fluent-bit -c ../dev-files/confs/out_otel_logs.conf
==13495==
Fluent Bit v2.0.7
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/12/15 07:47:47] [ info] [fluent bit] version=2.0.7, commit=91ebce5540, pid=13495
[2022/12/15 07:47:47] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/12/15 07:47:47] [ info] [cmetrics] version=0.5.7
[2022/12/15 07:47:47] [ info] [output:stdout:stdout.0] worker #0 started
[2022/12/15 07:47:47] [ info] [ctraces ] version=0.2.5
[2022/12/15 07:47:47] [ info] [input:dummy:dummy.0] initializing
[2022/12/15 07:47:47] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/12/15 07:47:47] [ info] [sp] stream processor started
^C[2022/12/15 07:47:48] [engine] caught signal (SIGINT)
[0] dummy.log: [1671090468.010704176, {"key"=>["val1", 1, 2.300000, [4, 4.600000, 2], {"mim"=>"mimvalue"}], "key2"=>"val2"}]
[2022/12/15 07:47:48] [ warn] [engine] service will shutdown in max 5 seconds
[2022/12/15 07:47:48] [ info] [input] pausing dummy.0
[2022/12/15 07:47:48] [ info] [output:opentelemetry:opentelemetry.1] 0.0.0.0:3434, HTTP status=200


[2022/12/15 07:47:48] [ info] [engine] service has stopped (0 pending tasks)
[2022/12/15 07:47:48] [ info] [input] pausing dummy.0
[2022/12/15 07:47:48] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/12/15 07:47:49] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==13495==
==13495== HEAP SUMMARY:
==13495==     in use at exit: 0 bytes in 0 blocks
==13495==   total heap usage: 1,828 allocs, 1,828 frees, 1,090,535 bytes allocated
==13495==
==13495== All heap blocks were freed -- no leaks are possible
==13495==
==13495== For lists of detected and suppressed errors, rerun with: -s
==13495== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

Signed-off-by: Aditya Prajapati <aditya@calyptia.com>

### CODE REVIEW

**Comment by edsiper** [comment]
@Syn3rman windows CI is failing, to review the PR we need at least CI passing

@leonardo-albertovich would you please review the PR once CI is ready ?

**Comment by edsiper** [comment]
@Syn3rman 

```
D:\a\fluent-bit\fluent-bit\plugins\out_opentelemetry\opentelemetry.c(697): error C2133: 'log_records': unknown size
D:\a\fluent-bit\fluent-bit\plugins\out_opentelemetry\opentelemetry.c(698): error C2057: expected constant expression
D:\a\fluent-bit\fluent-bit\plugins\out_opentelemetry\opentelemetry.c(698): error C2466: cannot allocate an array of constant size 0
D:\a\fluent-bit\fluent-bit\plugins\out_opentelemetry\opentelemetry.c(698): error C2133: 'log_bodies': unknown size
```

**Comment by Syn3rman** [comment]
@edsiper fixed, the failing tests are unrelated and should be adressed by #6569

@leonardo-albertovich this is now ready for review, I've moved the variables to heap and added check on batch_size (valgrind is happy too)

File: plugins/out_opentelemetry/opentelemetry.c [hunk 1]
```diff
@@ -689,29 +693,38 @@ static int process_logs(struct flb_event_chunk *event_chunk,
                         struct flb_input_instance *ins, void *out_context,
                         struct flb_config *config)
 {
-    Opentelemetry__Proto__Logs__V1__LogRecord *log_record_list[FLB_LOG_RECORD_BATCH_SIZE];
-    Opentelemetry__Proto__Logs__V1__LogRecord log_records[FLB_LOG_RECORD_BATCH_SIZE];
-    Opentelemetry__Proto__Common__V1__AnyValue log_bodies[FLB_LOG_RECORD_BATCH_SIZE];
+    struct opentelemetry_context *ctx;
+    ctx = out_context;
+
+    // These were initially variable length arrays.
```
Comment (edsiper) [inline plugins/out_opentelemetry/opentelemetry.c:699]: use /* for comments */, what's the issue number you are referring to here ?

File: plugins/out_opentelemetry/opentelemetry.c [hunk 2]
```diff
@@ -689,29 +693,38 @@ static int process_logs(struct flb_event_chunk *event_chunk,
...
     msgpack_unpacked result;
     msgpack_object *obj;
     size_t off = 0;
     struct flb_time tm;
-    char *json;
     int res = FLB_OK;
-    struct opentelemetry_context *ctx;
 
-    for(index = 0 ; index < FLB_LOG_RECORD_BATCH_SIZE ; index++) {
+    log_record_list = (Opentelemetry__Proto__Logs__V1__LogRecord *) flb_calloc(ctx->batch_size, sizeof(Opentelemetry__Proto__Logs__V1__LogRecord *));
```
Comment (edsiper) [inline plugins/out_opentelemetry/opentelemetry.c:717]: validate all memory allocations

File: plugins/out_opentelemetry/opentelemetry.h [hunk 3]
```diff
@@ -31,7 +31,7 @@
  * log records, and a later batch fails, Fluent Bit will retry ALL the batches,
  * including the ones that succeeded. This is not ideal.
  */
-#define FLB_LOG_RECORD_BATCH_SIZE 1000
+#define DEFAULT_LOG_RECORD_BATCH_SIZE "64"
```
Comment (edsiper) [inline plugins/out_opentelemetry/opentelemetry.h:34]: isn't "64" too low ?

**Review by edsiper — CHANGES_REQUESTED** [review]

File: plugins/out_opentelemetry/opentelemetry.h (hunk 3 above)
Comment (Syn3rman) [reply plugins/out_opentelemetry/opentelemetry.h:34]: Oh yeah should be fine since it is on the heap now

File: plugins/out_opentelemetry/opentelemetry.c (hunk 1 above)
Comment (Syn3rman) [reply plugins/out_opentelemetry/opentelemetry.c:699]: #6512 
When it was a variable length array stored on the stack, the event chunk was being corrupted somewhere between 720 & 730 [initialisation](https://github.com/fluent/fluent-bit/blob/46bb7845817a37fef3fc01b9ebd54797c192419b/plugins/out_opentelemetry/opentelemetry.c#L721)

**Review by edsiper — APPROVED** [review]

**Comment by edsiper** [comment]
merged as  #6583 (this CI is stuck)
