### PR TITLE
Fix build on macOS 10.15

### LINKED ISSUE #2220: Unable to build on Mac OS 10.15
## Bug Report

**Describe the bug**
Unable to build fluentbit from source on MacOS 10.15 

**To Reproduce**

Getting this error.

```
[  3%] Built target flb-plugin-proxy-go
[  3%] Performing build step for 'luajit'
==== Building LuaJIT 2.1.0-beta3 ====
HOSTCC    host/minilua.o
host/minilua.c:34:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
make[4]: *** [host/minilua.o] Error 1
make[3]: *** [default] Error 2
make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
```

**Expected behavior**
Should be build without any issues

**Your Environment**

* Version used: 1.5 latest (on master)
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): Local Setup
* Server type and version:
* Operating System and version: Mac OS Catalina 10.15.2
* Filters and plugins: No plugins

cc @edsiper

### PR DESCRIPTION
**Pull request by lht**
Fix build error on macOS 10.15

Fixes #2220

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A ] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -32,6 +32,8 @@ if (MSVC)
   # Use add_compile_options() to set /MT since Visual Studio
   # Generator does not notice /MT in CMAKE_C_FLAGS.
   add_compile_options(/MT)
+elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
+  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -fno-common")
```
Comment (lht) [inline CMakeLists.txt:36]: Without this, linking failed with below error.
```
[ 85%] Linking C executable ../bin/fluent-bit
Undefined symbols for architecture x86_64:
  "_flb_thread_key", referenced from:
      _flb_main in fluent-bit.c.o
      _flb_engine_start in libfluent-bit.a(flb_engine.c.o)
      _flb_input_collector_fd in libfluent-bit.a(flb_input.c.o)
      _flb_engine_dispatch_retry in libfluent-bit.a(flb_engine_dispatch.c.o)
      _tasks_start in libfluent-bit.a(flb_engine_dispatch.c.o)
      _flb_output_return_do in libfluent-bit.a(flb_plugin_proxy.c.o)
      _create_conn in libfluent-bit.a(flb_upstream.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Although symbol `_flb_thread_key` is indeed included in libfluent-bit.a
```
❯ nm ./library/libfluent-bit.a | rg flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
0000000000000008 C _flb_thread_key
                 U _flb_thread_key
```
As suggested by [this thread](https://github.com/libigl/libigl/issues/751#issuecomment-383324059), using flag `-fno-common` will enforce the uninitialized variable not be put in common section.

```
❯ nm ./library/libfluent-bit.a| rg flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
                 U _flb_thread_key
0000000000000080 S _flb_thread_key
                 U _flb_thread_key
```

Comment (bluebike) [reply CMakeLists.txt:36]: I think problem with in  /include/fluent-bit/flb_thread.h:37

Line: 
`extern FLB_EXPORT pthread_key_t flb_thread_key`

Should be:
`FLB_EXPORT pthread_key_t flb_thread_key;`

Comment (lht) [reply CMakeLists.txt]: Thanks for the pointer, @bluebike! That's indeed what caused the issue, introduced by https://github.com/fluent/fluent-bit/commit/328982390b04e81f459f742362dbff56bb6dcb54

PR updated with the fix you suggested.

**Comment by edsiper** [comment]
the solution provided breaks the build using GCC 10. 

Restoring the ```extern``` builds fine on Linux, would you please re-check in macos ?

**Comment by bluebike** [comment]
I think that only flb_thread.h fix is needed.

(I got also problems if I had /usr/local/bin with homebrew stuff there in path before system stuff)

**Comment by edsiper** [comment]
we need a clean solution that don't break Linux build 

which clang version your macos is using ?

**Comment by lht** [comment]
> which clang version your macos is using ?

Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

File: CMakeLists.txt (hunk 1 above)
Comment (lht) [reply CMakeLists.txt:36]: @edsiper I restored my initial attempted solution that append flag `-fno-common` on Darwin.

clang has made[ `-fno-common` default](https://github.com/llvm/llvm-project/commit/0a9fc9233e172601e26381810d093e02ef410f65) to be aligned with GCC 10. It'll be included in the next release.
