### ISSUE TITLE
[1.6.10] cmake fails to create `monkey/mk_info.h`, compilation fails

### ISSUE THREAD

**Issue by girgen** [fluent/fluent-bit#2930]
## Bug Report

**Describe the bug**
cmake fails to create `monkey/mk_info.h` and as a result, the compilation fails.

**To Reproduce**
git checkout 1.6
cd build
cmake ..
make

**Expected behavior**

cmake would generate `.h` header files from `.h.in` files, and then make would politely build fluent-bit

**Screenshots**
```
[ 82%] Built target flb-plugin-in_collectd
Scanning dependencies of target flb-plugin-in_http
[ 83%] Building C object plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http.c.o
In file included from /Users/girgen/repos/fluent-bit/plugins/in_http/http.c:26:
In file included from /Users/girgen/repos/fluent-bit/plugins/in_http/http.h:28:
In file included from /Users/girgen/repos/fluent-bit/lib/monkey/include/monkey/monkey.h:43:
In file included from /Users/girgen/repos/fluent-bit/lib/monkey/include/monkey/mk_server.h:24:
In file included from /Users/girgen/repos/fluent-bit/lib/monkey/include/monkey/mk_socket.h:31:
/Users/girgen/repos/fluent-bit/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: 'monkey/mk_info.h' file not found
#include <monkey/mk_info.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http.c.o] Error 1
make[1]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/all] Error 2
make: *** [all] Error 2
```

**Your Environment**

* Version used: 1.6.10
* Configuration: BSD (FreeBSD and Mac OS both fail)
* Environment name and version (e.g. Kubernetes? What version?): FreeBSD (all versions), Mac OS X
* Server type and version: FreeBSD
* Operating System and version: FreeBSD
* Filters and plugins: n/a

**Additional context**
Note that 1.6.9 does build as does master. The issue is specific to version 1.6.10.

**Comment by chenrui333** [comment]
I have run into the same build issue. cc @@edsiper

**Comment by girgen** [comment]
I tried a few different versions of cmake. The problem is exactly when upgrading from 1.6.9. to 1.6.10.

**Comment by herbygillot** [comment]
I'm seeing the same, specifically with *1.6.10*, also buildong on macOS Catalina.

```
cd /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build/plugins/in_http && /usr/bin/clang -DFLB_HAVE_AWS -DFLB_HAVE_CLOCK_GET_TIME -DFLB_HAVE_FORK -DFLB_HAVE_GMTOFF -DFLB_HAVE_LIBBACKTRACE -DFLB_HAVE_LUAJIT -DFLB_HAVE_PARSER -DFLB_HAVE_PROXY_GO -DFLB_HAVE_RECORD_ACCESSOR -DFLB_HAVE_REGEX -DFLB_HAVE_SIGNV4 -DFLB_HAVE_SQLDB -DFLB_HAVE_STREAM_PROCESSOR -DFLB_HAVE_TIMESPEC_GET -DFLB_HAVE_TLS -DFLB_HAVE_UTF8_ENCODER -DJSMN_PARENT_LINKS -DJSMN_STRICT -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/flb_libco -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/rbtree -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/msgpack-3.2.0/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/chunkio/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/luajit-2.1.0-dd5032e/src -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/mbedtls-2.24.0/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/sqlite-amalgamation-3330000 -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/mpack-amalgamation-1.0/src -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/miniz -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/onigmo -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/tutf8e/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build/backtrace-prefix/include -I/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build/lib/msgpack-3.2.0/include -pipe -Os -DNDEBUG -I/opt/macports-test/include -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wall -fno-common -D__FILENAME__='"plugins/in_http/http.c"' -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.15 -fPIC -o CMakeFiles/flb-plugin-in_http.dir/http.c.o -c /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http.c
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http_config.c:23:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http.h:28:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/monkey.h:43:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_server.h:24:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_socket.h:31:
/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: 'monkey/mk_info.h' file not found
#include <monkey/mk_info.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http.c:26:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http.h:28:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/monkey.h:43:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_server.h:24:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_socket.h:31:
/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: 'monkey/mk_info.h' file not found
#include <monkey/mk_info.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http_conn.c:24:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http.h:28:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/monkey.h:43:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_server.h:24:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_socket.h:31:
/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: 'monkey/mk_info.h' file not found
#include <monkey/mk_info.h>
         ^~~~~~~~~~~~~~~~~~
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/plugins/in_http/http_prot.c:26:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/monkey.h:43:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_server.h:24:
In file included from /opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_socket.h:31:
/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: 'monkey/mk_info.h' file not found
#include <monkey/mk_info.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http_config.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http.c.o] Error 1
1 error generated.
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http_conn.c.o] Error 1
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http_prot.c.o] Error 1
make[2]: Leaving directory `/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build'
make[1]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/all] Error 2
make[1]: Leaving directory `/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build'
make: *** [all] Error 2
make: Leaving directory `/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build'
Command failed:  cd "/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_sysutils_fluent-bit/fluent-bit/work/build" && /usr/bin/make -j16 -w VERBOSE=ON
```

**Comment by AnujAroshA** [comment]
Having the same issue.

**OS**
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

When run the **_make_** command gets following error

```
Scanning dependencies of target flb-plugin-in_http
[ 75%] Building C object plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http.c.o
In file included from /home/parallels/FluentBit/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_socket.h:31,
                 from /home/parallels/FluentBit/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_server.h:24,
                 from /home/parallels/FluentBit/fluent-bit-1.6.10/lib/monkey/include/monkey/monkey.h:43,
                 from /home/parallels/FluentBit/fluent-bit-1.6.10/plugins/in_http/http.h:28,
                 from /home/parallels/FluentBit/fluent-bit-1.6.10/plugins/in_http/http.c:26:
/home/parallels/FluentBit/fluent-bit-1.6.10/lib/monkey/include/monkey/mk_config.h:26:10: fatal error: monkey/mk_info.h: No such file or directory
   26 | #include <monkey/mk_info.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/build.make:63: plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/http.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3176: plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by nokute78** [comment]
The workaround is to disable `in_http` plugin.
It is enabled on v1.6.10.

```
cmake .. -DFLB_IN_HTTP=no 
make
```

**Comment by herbygillot** [comment]
> The workaround is to disable `in_http` plugin.
> It is enabled on v1.6.10.
> 
> ```
> cmake .. -DFLB_IN_HTTP=no 
> make
> ```

Confirmed that resolves the issue... I wonder will `in_http` be turned off again in the next release...

**Comment by BatmansByte** [comment]
Still, version 1.6.10

Did the above, 
cmake .. -DFLB_IN_HTTP=no 
make

got
Scanning dependencies of target fluent-bit-bin
[ 85%] Building C object src/CMakeFiles/fluent-bit-bin.dir/fluent-bit.c.o
[ 85%] Building C object src/CMakeFiles/fluent-bit-bin.dir/flb_dump.c.o
make[2]: *** No rule to make target 'lib/libonigmo.a', needed by 'bin/fluent-bit'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:5331: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

..\cmake\onigmo.cmake seems to match https://github.com/fluent/fluent-bit/blob/master/cmake/onigmo.cmake

Not a programmer, I admit it.
Thanks if you'll help.

**Comment by nokute78** [comment]
@BatmansByte 

1. Could you try to build after `make clean` ?
1. What is your environment ? 
1. Could you share full build log?

**Comment by BatmansByte** [comment]
1) I've used make clean. On occasion, I've simple deleted  the directory tree and un-tarzipped the file anew.

2) I was using OpenSuse Leap 15.1 with CMake 10.3 I think.
I took the hint and upgraded to Leap 15.2 (Kernel 5.3.10-lp152.60-default) with CMake 3.17.0 and GNU Make 4.2.1
Still the same problems.

I still get the http error noted above.
onigmo seems to be part of the regex module, used by the parser module.
I've tried building with cmake .. -DFLB_HTTP_IN=no  -DFLB_FILTER_GREP -DFLB_FILTER_PARSER, still same problems.
Must be something else using regex in the make build.

3) Not sure what you mean by full build log. 
I've attached the CMake Output and Error Logs. Also a Directory Listing of the CMakeFiles directory.

[CMakeError.log](https://github.com/fluent/fluent-bit/files/5909128/CMakeError.log)
[CMakeOutput.log](https://github.com/fluent/fluent-bit/files/5909129/CMakeOutput.log)
[CMakeFilesDirList.txt](https://github.com/fluent/fluent-bit/files/5909160/CMakeFilesDirList.txt)
and here's make's output.

make 2>&1 | tee build.log
[build.log](https://github.com/fluent/fluent-bit/files/5909225/build.log)

I was hoping to use this as a basis for a NewRelic plugin, but it turned out that NewRelic's tarball includes a working (for it's purposes) version of fluentbit, so I didn't need this after all. Still not all that good at reading directions, I guess, though the problem was that I didn't really understand them. Still, If you want to keep troubleshooting this to diagnose the fluent bit issue, I'll continue to help in any way that I can.

Thank you for your willingness to help me.
Kirk B.

**Comment by nokute78** [comment]
@BatmansByte Thank you for sharing logs.

Refer to your build.log, libonigmo.a is installed under `lib64` dir.
```
libtool: install: ranlib /home/batman/Admin/NewRelic/fluent-bit-1.6.10/build/lib64/libonigmo.a
```

onigmo.cmake sets the path like this. It expects under `lib` dir.
https://github.com/fluent/fluent-bit/blob/804f2af1002b9608a8a2994233583eaf22ad45ba/cmake/onigmo.cmake#L67

Could you try to modify the line like `"${ONIGMO_DEST}/lib64/libonigmo.a"` ?

**Comment by BatmansByte** [comment]
Tried editing onigmo.make as specified, there were two "set" lines in an if/else, modified both of them from lib to lib64.

Then it make clean and re-cmake (no http) and it bombed out again with a similar error for backtrace/backtrace-prefix

make clean, cmake .. ,etc. again, and 
modified CMakeLists.txt similarly, changing lib to lib64 on or about line 624
set_target_properties(libbacktrace PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/backtrace-prefix/lib/libbacktrace.a")
under
# LibBacktrace (friendly stacktrace support)
# =========================================

After that, I was able to complete the build and even sudo make install.

Was able to cd into /usr/local and run 
fluent-bit -i cpu -o stdout 
and got reasonable output.

Hardly a complete test of all features, but definitely progress.
Kirk B.

Not a

**Comment by nokute78** [comment]
@BatmansByte  Thank you for testing.
So, replacing lib -> lib64 in some cmake files may be a workaround for OpenSUSE leap.

I think some cmake variables caused your issue, but currently I can't find that..

**Comment by chenrui333** [comment]
just FYI, `v1.7.0` build successfully on the [homebrew side](https://github.com/Homebrew/homebrew-core/pull/71167)
