### ISSUE TITLE
Unable to build on Mac OS 10.15

### ISSUE THREAD

**Issue by championshuttler** [fluent/fluent-bit#2220]
## Bug Report

**Describe the bug**
Unable to build fluentbit from source on MacOS 10.15 

**To Reproduce**

Getting this error.

```
[  3%] Built target flb-plugin-proxy-go
[  3%] Performing build step for 'luajit'
==== Building LuaJIT 2.1.0-beta3 ====
HOSTCC    host/minilua.o
host/minilua.c:34:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
make[4]: *** [host/minilua.o] Error 1
make[3]: *** [default] Error 2
make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
```

**Expected behavior**
Should be build without any issues

**Your Environment**

* Version used: 1.5 latest (on master)
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): Local Setup
* Server type and version:
* Operating System and version: Mac OS Catalina 10.15.2
* Filters and plugins: No plugins

cc @edsiper

**Comment by koleini** [comment]
Have you tried `xcode-select --install`?

**Comment by championshuttler** [comment]
@koleini yeah I did , still the same problem

**Comment by edsiper** [comment]
Maybe this is relevant:

https://github.com/fluent/fluent-bit/issues/1407#issuecomment-506195564

**Comment by edsiper** [comment]
fixed on #2303
