### ISSUE TITLE
Changes in v2.0.0+ break static compilation on armhf

### ISSUE THREAD

**Issue by brian-maloney** [fluent/fluent-bit#6307]
## Bug Report

**Describe the bug**
Changes in v2.0.0+ break static compilation on `armhf`.

I have been building statically-compiled Fluent-Bit on the 4 supported platforms (i386, amd64, armhf, arm64) for a while now in [this project](https://github.com/brian-maloney/fluent-bit-static).  I use Docker with a Debian bullseye base to build my binaries. 
 With the release of v2.0.0 all my builds broke.

After some research, I tracked down that changes in `fb_hash` to directly use OpenSSL instead of Monkey required me to add `libssl-dev` to my build image, which caused further downstream issues requiring me to then disable WASM and LUAJIT.  All of these are acceptable for my use case, but while I was able to solve the issues in most general cases, I am stuck on a linking issue with `armhf`.

**To Reproduce**
- Link error:
```
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libc.a(getcontext.o): in function `__getcontext':
(.text+0x74): undefined reference to `_rtld_global_ro'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libc.a(setcontext.o): in function `__startcontext':
(.text+0x80): undefined reference to `_rtld_global_ro'
```
- Steps to reproduce the problem:
```
git clone https://github.com/brian-maloney/fluent-bit-static.git
cd fluent-bit-static
docker build --progress plain --build-arg "TAG=v2.0.0" --build-arg "BUILDARCH=armhf" --platform 'linux/arm/v7' -t fluent-bit-static .
```

**Expected behavior**
Successful build and link

**Your Environment**

* Version used: 2.0.0
* Configuration: Build in Docker

**Additional context**

I understand this isn't a directly supported use case, and I'm looking for some unusual assistance, but I'd love to avoid having to drop `armhf` support on these builds that I supply to the community.

**Comment by edsiper** [comment]
hi @brian-maloney, sorry about this problem, not sure what can be. We will assign one maintainer to track it down.

**Comment by edsiper** [comment]
assigned to @nokute78

**Comment by edsiper** [comment]
note: please use v2.0.3

**Comment by nokute78** [comment]
@brian-maloney I can't build an image. Could you share full docker build log ?
I tried to build on Ubuntu 22.04 on Virtualbox. I may need an arm or native Linux host.

```
c$ sudo docker build --progress plain --build-arg "TAG=v2.0.0" --build-arg "BUILDARCH=armhf" --platform 'linux/arm/v7' -t fluent-bit-static .
Sending build context to Docker daemon  84.48kB
Step 1/16 : FROM debian:latest as build
latest: Pulling from library/debian
a9bec1cbb822: Already exists 
Digest: sha256:bfe6615d017d1eebe19f349669de58cda36c668ef916e618be78071513c690e5
Status: Downloaded newer image for debian:latest
 ---> cda55ae8bb0c
Step 2/16 : ARG TAG
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in e4ab0e034b2e
Removing intermediate container e4ab0e034b2e
 ---> 54da099207f7
Step 3/16 : ARG TARGETARCH
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 450bd05903af
Removing intermediate container 450bd05903af
 ---> 9c98108491b6
Step 4/16 : RUN test -n "$TAG" || (echo "TAG not set" && false)
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 7a291c2971e8
exec /bin/sh: exec format error
The command '/bin/sh -c test -n "$TAG" || (echo "TAG not set" && false)' returned a non-zero code: 1
```

My host and docker info:
```
$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by brian-maloney** [comment]
Hi @nokute78, thanks for taking a look at this!  If you're running on AMD64 Ubuntu you'll need to run this command before you get to work, apologies for not warning you about it earlier: `sudo apt install qemu-user-static`.

When I'm debugging this I usually use an ARM Linux machine so builds go faster (AWS Spot c7g instances are very inexpensive) but as long as you don't do complete rebuilds, emulation should be okay.  For example I sometimes run `docker run -it --rm --platform 'linux/arm/v7' debian:bullseye` and do builds from a shell.

I hope this helps and once again thank you for taking a look at this issue.

**Comment by nokute78** [comment]
@brian-maloney  Thank you for information.

I tried to build v2.0.3 and it failed.

```
[100%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libfluent-bit.a(flb_plugin.c.o): in function `get_handle':
/tmp/build/fluent-fluent-bit-86250fa/src/flb_plugin.c:75: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../lib/monkey/library/libmonkey.a(mk_user.c.o): in function `mk_user_set_uidgid':
/tmp/build/fluent-fluent-bit-86250fa/lib/monkey/mk_server/mk_user.c:114: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../library/libchunkio-static.a(cio_file_unix.c.o): in function `cio_file_native_lookup_group':
/tmp/build/fluent-fluent-bit-86250fa/lib/chunkio/src/cio_file_unix.c:242: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../lib/monkey/library/libmonkey.a(mk_user.c.o): in function `mk_user_init':
/tmp/build/fluent-fluent-bit-86250fa/lib/monkey/mk_server/mk_user.c:65: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../library/libchunkio-static.a(cio_file_unix.c.o): in function `cio_file_native_lookup_user':
/tmp/build/fluent-fluent-bit-86250fa/lib/chunkio/src/cio_file_unix.c:180: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../library/libfluent-bit.a(flb_network.c.o): in function `flb_net_bind_address':
/tmp/build/fluent-fluent-bit-86250fa/src/flb_network.c:1137: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
(.text+0x64): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../lib/c-ares-1.18.1/lib/libcares.a(ares_getaddrinfo.c.o): in function `lookup_service':
/tmp/build/fluent-fluent-bit-86250fa/lib/c-ares-1.18.1/src/lib/ares_getaddrinfo.c:249: warning: Using 'getservbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: ../lib/c-ares-1.18.1/lib/libcares.a(ares_getnameinfo.c.o): in function `lookup_service':
/tmp/build/fluent-fluent-bit-86250fa/lib/c-ares-1.18.1/src/lib/ares_getnameinfo.c:300: warning: Using 'getservbyport_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libc.a(getcontext.o): in function `__getcontext':
(.text+0x74): undefined reference to `_rtld_global_ro'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libc.a(setcontext.o): in function `__startcontext':
(.text+0x80): undefined reference to `_rtld_global_ro'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:361: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:7003: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
The command '/bin/sh -c cd fluent*/build &&     cmake -DFLB_WASM=No -DFLB_LUAJIT=No -DFLB_DEBUG=No -DFLB_RELEASE=Yes -DFLB_SHARED_LIB=No -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static" -DOPENSSL_USE_STATIC_LIBS=Yes -DCMAKE_C_FLAGS="-fcommon" .. &&     make &&     strip bin/fluent-bit &&     cp bin/fluent-bit "/tmp/fluent-bit-${TAG}-${TARGETARCH}"' returned a non-zero code: 2

```

**Comment by nokute78** [comment]
I built `TAG=v2.0.3`, `TAG=v2.0.0`, `TAG=v1.9.9` and `TAG=v1.9.0`.
Build failed in all versions and reported same the link error.

@brian-maloney What is the version you build successfully ?

**Comment by brian-maloney** [comment]
@nokute78 Version 1.9.9 (and below) build successfully.  You will need to use an older version of the Dockerfile (before I added things to adapt to the changes to `flb_hash`.  

For example, to build 1.9.9:
```
git clone https://github.com/brian-maloney/fluent-bit-static.git
cd fluent-bit-static
git checkout tags/v1.9.9
docker build --progress plain --build-arg "TAG=v1.9.9" --build-arg "BUILDARCH=armhf" --platform 'linux/arm/v7' -t fluent-bit-static .
```

**Comment by nokute78** [comment]
@brian-maloney Thank you for pointing it.
I tried it and there was no link error.

By the way, I found a glibc issue. It is not closed.
https://sourceware.org/bugzilla/show_bug.cgi?id=24529

Following page reported that building glibc addressed the issue.
https://stackoverflow.com/questions/62896208/linking-issue-using-the-yocto-sdk-undefined-reference-to-rtld-global-ro

**Comment by brian-maloney** [comment]
Although the glibc issue is still open, it looks like the relevant change is present in glibc 2.35 and above.  I tested using `debian:sid` for the build Docker image and it works!  I'm trying now with `bookworm` but I believe that this will work as well.

I'm going to close this as it's conclusively a bug/issue in glibc, not fluent-bit.  Thank you very much for your time in helping me track this down!
