### PR TITLE
Avoid using reserved keyword delete

### PR DESCRIPTION
**Pull request by cschug**
Unbreak build on CentOS 7/x86_64 using gcc 4.8.5 by renaming `delete` to just `del`.
```
In file included from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_input.h:24:0,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_engine.h:26,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_output.h:37,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit.h:38,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/examples/hello_world_cpp/hello_world.cc:20:
/builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_input_chunk.h:39:61: error: expected ',' or '...' before 'delete'
 int flb_input_chunk_destroy(struct flb_input_chunk *ic, int delete);
                                                             ^
In file included from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_output.h:38:0,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit.h:38,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/examples/hello_world_cpp/hello_world.cc:20:
/builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_task.h:111:50: error: expected ',' or '...' before 'delete'
 void flb_task_destroy(struct flb_task *task, int delete);
                                                  ^
make[2]: *** [examples/hello_world_cpp/CMakeFiles/hello_world_cpp.dir/hello_world.cc.o] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/fluent-bit-1.0.0/build'
make[1]: *** [examples/hello_world_cpp/CMakeFiles/hello_world_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_input.h:24:0,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_engine.h:26,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_output.h:37,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit.h:38,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/examples/td_cpp/td.cc:21:
/builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_input_chunk.h:39:61: error: expected ',' or '...' before 'delete'
 int flb_input_chunk_destroy(struct flb_input_chunk *ic, int delete);
                                                             ^
In file included from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_output.h:38:0,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit.h:38,
                 from /builddir/build/BUILD/fluent-bit-1.0.0/examples/td_cpp/td.cc:21:
/builddir/build/BUILD/fluent-bit-1.0.0/include/fluent-bit/flb_task.h:111:50: error: expected ',' or '...' before 'delete'
 void flb_task_destroy(struct flb_task *task, int delete);
                                                  ^
make[2]: *** [examples/td_cpp/CMakeFiles/td.dir/td.cc.o] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/fluent-bit-1.0.0/build'
make[1]: *** [examples/td_cpp/CMakeFiles/td.dir/all] Error 2
```

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for contributing this PR. in the meanwhile this PR arrived, two commits were already in place to solve the problem. 

thanks again for your help.
